'use strict'

// Generates CALLBACKS.md from api.lua.
//
// WHY A GENERATOR, and why not another hand-written table in DOCUMENTATION.md
//
// The third permanent commitment is "one contract, several consumers. Docs,
// types, changelogs, the storefront and the support bot are all generated from
// the same source." api.lua IS that source -- CI already validates it against
// what the code actually registers -- and the event and callback dictionary is
// exactly the artefact a support bot quotes from.
//
// A hand-written table goes stale silently. Nothing fails, the table disagrees
// with the code, and the reader believes the table because a table is what
// documentation looks like. So this writes it, and `--check` fails when the
// committed file is not what the generator produces.
//
// The generated file is COMMITTED rather than built at boot. Documentation that
// only exists after you start a server is documentation nobody reads before they
// start one.
//
// Usage:
//   node tools/gen-docs.js           write CALLBACKS.md
//   node tools/gen-docs.js --check   fail if the committed file is stale

const fs = require('fs')
const path = require('path')
const fengari = require('fengari')

const { lua, lauxlib, lualib } = fengari
const toLua = fengari.to_luastring

const root = path.join(__dirname, '..')
const apiFile = path.join(root, 'api.lua')
const outFile = path.join(root, 'CALLBACKS.md')

// Load api.lua the way tools/validate-api.js does: it is DATA that returns a
// table, so `lua_call` with one result leaves it on the stack, and a walker
// turns it into JS. Anything in api.lua that had a side effect would be a defect
// in the contract, and this is the one place that would notice.
function loadApi() {
  const L = lauxlib.luaL_newstate()
  lualib.luaL_openlibs(L)
  const src = fs.readFileSync(apiFile, 'utf8')
  const status = lauxlib.luaL_loadbuffer(L, toLua(src), null, toLua('api.lua'))
  if (status !== lua.LUA_OK) {
    return { error: lua.lua_tojsstring(L, -1) }
  }
  lua.lua_call(L, 0, 1)
  return { table: readValue(L, -1) }
}

// Walk the Lua value at `index` into JS. api.lua is shallow -- strings, numbers,
// booleans and one level of nested tables -- so this is deliberately simple and
// says so rather than pretending to be a general serialiser.
function readValue(L, index) {
  const type = lua.lua_type(L, index)
  if (type === lua.LUA_TNIL || type === lua.LUA_TNONE) return null
  // fengari's lua_toboolean returns a JS BOOLEAN, not 0/1. `!== 0` is always
  // true -- which marked every export in the generated doc as deprecated,
  // because every `deprecated = false` in api.lua read as true.
  if (type === lua.LUA_TBOOLEAN) return lua.lua_toboolean(L, index) === true
  if (type === lua.LUA_TNUMBER) return lua.lua_tonumber(L, index)
  if (type === lua.LUA_TSTRING) return lua.lua_tojsstring(L, index)
  if (type !== lua.LUA_TTABLE) return null

  const out = {}
  const abs = lua.lua_absindex(L, index)
  lua.lua_pushnil(L)
  while (lua.lua_next(L, abs) !== 0) {
    const key = lua.lua_tojsstring(L, -2)
    const value = readValue(L, -1)
    lua.lua_settop(L, -2)
    out[key] = value
  }
  return out
}

// A pipe inside a Markdown table cell breaks the row, and api.lua's `use`
// strings are prose. Escaped rather than stripped: a reader who copies the cell
// should get the character.
function cell(text) {
  return String(text === undefined || text === null ? '' : text).replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

function render(api) {
  const L = []
  const push = (line) => L.push(line)

  push('<!-- GENERATED by tools/gen-docs.js from api.lua. Do not edit by hand. -->')
  push('')
  push('# cis_core — exports, events and commands')
  push('')
  push(`**Contract major:** \`api = ${api.api}\` &nbsp;·&nbsp; **Product version:** \`${api.version}\``)
  push('')
  push('Generated from [`api.lua`](api.lua), which CI validates against what the code')
  push('actually registers. A row here that does not work is a **build failure**, not a')
  push('documentation bug — and this file is checked for staleness on every push.')
  push('')
  push('---')
  push('')

  // ---------------------------------------------------------------- exports
  const names = Object.keys(api.exports || {})
  names.sort()

  const byRealm = { server: [], client: [], both: [] }
  for (const name of names) {
    const meta = api.exports[name] || {}
    byRealm[(meta.realm || 'server')].push(name)
  }

  push('## Exports')
  push('')
  push('A consumer calls `exports[\'cis_core\']:Name(...)`. **Every export can return')
  push('`false, reason`**, and a reason is a sentence an operator can act on — so check')
  push('it, and print it.')
  push('')

  for (const realm of ['server', 'client', 'both']) {
    const list = byRealm[realm]
    if (list.length === 0) continue
    push(`### ${realm[0].toUpperCase()}${realm.slice(1)} realm`)
    push('')
    if (realm === 'both') {
      push('> Registered on both realms. `api = 1` says a caller does not branch on')
      push('> `IsDuplicityVersion()` to choose which to call.')
      push('')
    }
    push('| Export | Signature | Since | What it is for |')
    push('|---|---|---|---|')
    for (const name of list) {
      const meta = api.exports[name] || {}
      const flag = meta.deprecated ? '**Deprecated.** ' : ''
      push(`| \`${name}\` | \`${meta.signature || '?'}\` | ${meta.since || '?'} | ${flag}${cell(meta.use)} |`)
    }
    push('')
  }

  // ----------------------------------------------------------------- events
  const events = Object.keys(api.events || {})
  events.sort()
  push('## Events listened for')
  push('')
  push('`cis_core` publishes **no** net events. A product that wants a notification or')
  push('an inventory push calls an export instead, so the wire stays in the one place')
  push('that owns it.')
  push('')
  push('| Event | Since | Payload |')
  push('|---|---|---|')
  for (const name of events) {
    const meta = api.events[name] || {}
    push(`| \`${name}\` | ${meta.since || '?'} | ${cell(meta.payload)} |`)
  }
  push('')

  // --------------------------------------------------------------- commands
  const cmds = Object.keys(api.commands || {})
  cmds.sort()
  push('## Console commands')
  push('')
  if (cmds.length === 0) {
    push('_None._')
    push('')
  } else {
    push('| Command | Since | Who may run it | What it is for |')
    push('|---|---|---|---|')
    for (const name of cmds) {
      const meta = api.commands[name] || {}
      push(
        `| \`${name}\` | ${meta.since || '?'} | ${
          meta.restricted ? 'console, or an admin in game' : '**anyone**'
        } | ${cell(meta.use)} |`,
      )
    }
    push('')
    push('A refusal is **silence**, not a message. A command that tells a stranger what')
    push('this server runs is a command that should not exist.')
    push('')
  }

  push('---')
  push('')
  push('The full prose version, with the reasoning behind each decision, is in')
  push('[`DOCUMENTATION.md`](DOCUMENTATION.md). What an upgrade costs you is in')
  push('[`MIGRATION.md`](MIGRATION.md).')
  push('')

  return L.join('\n')
}

const loaded = loadApi()
if (loaded.error) {
  console.error(`api.lua did not load: ${loaded.error}`)
  process.exit(1)
}

const body = render(loaded.table)

if (process.argv.includes('--check')) {
  const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : ''
  if (existing !== body) {
    console.error('CALLBACKS.md is out of date. Run: node tools/gen-docs.js')
    process.exit(1)
  }
  console.log(`CALLBACKS.md is current (${body.split('\n').length} lines)`)
} else {
  fs.writeFileSync(outFile, body)
  console.log(`wrote CALLBACKS.md (${body.split('\n').length} lines)`)
}